import {createContext,useContext,useEffect,useMemo,useState,type ReactNode} from 'react';
import type {GrowthStory,Profile,StoryRecord} from './types';
const seed:StoryRecord[]=[
 {id:'first-ultrasound',type:'checkup',title:'처음 만난 작은 콩콩이',body:'화면 속 작은 심장이 또렷하게 뛰고 있었다. 말없이 손을 꼭 잡았던 순간을 오래 기억하고 싶다.',emotion:'설렘',date:'2026-08-12',weekOrAge:'11주 6일',author:'엄마',milestone:'첫 초음파',createdAt:3,color:'lavender'},
 {id:'first-heart',type:'daily',title:'두 줄을 처음 마주한 아침',body:'아직 믿기지 않아 몇 번이나 다시 바라봤다. 우리에게 찾아온 첫 소식을 조용히 품었다.',emotion:'감동',date:'2026-07-02',weekOrAge:'6주 1일',author:'엄마',milestone:'임신 확인',createdAt:2,color:'pink'},
 {id:'letter-one',type:'letter',title:'콩콩이에게 보내는 첫 편지',body:'건강하게 천천히 만나자. 엄마 아빠는 네가 오는 매일을 함께 기다리고 있어.',emotion:'행복',date:'2026-06-22',weekOrAge:'4주 5일',author:'배우자',createdAt:1,color:'sage'}];
type Ctx={profile?:Profile;records:StoryRecord[];stories:GrowthStory[];setProfile:(p:Profile)=>void;addRecord:(r:StoryRecord)=>void;updateRecord:(r:StoryRecord)=>void;restoreRecord:(id:string)=>void;addStory:(s:GrowthStory)=>void};
const Context=createContext<Ctx|null>(null);
export function Store({children}:{children:ReactNode}){const [profile,setP]=useState<Profile|undefined>(()=>JSON.parse(localStorage.getItem('ofs-profile')||'null')||undefined);const [records,setR]=useState<StoryRecord[]>(()=>JSON.parse(localStorage.getItem('ofs-records')||'null')||seed);const[stories,setS]=useState<GrowthStory[]>(()=>JSON.parse(localStorage.getItem('ofs-stories')||'[]'));useEffect(()=>localStorage.setItem('ofs-records',JSON.stringify(records)),[records]);useEffect(()=>localStorage.setItem('ofs-stories',JSON.stringify(stories)),[stories]);const value=useMemo(()=>({profile,records,stories,setProfile:(p:Profile)=>{setP(p);localStorage.setItem('ofs-profile',JSON.stringify(p));},addRecord:(r:StoryRecord)=>setR(x=>[r,...x]),updateRecord:(r:StoryRecord)=>setR(x=>x.map(v=>v.id===r.id?r:v)),restoreRecord:(id:string)=>setR(x=>{const source=x.find(r=>r.id===id);return source?[{...source,id:crypto.randomUUID(),title:`${source.title} · 복원본`,createdAt:Date.now()},...x]:x}),addStory:(s:GrowthStory)=>setS(x=>[s,...x.filter(v=>v.id!==s.id)])}),[profile,records,stories]);return <Context.Provider value={value}>{children}</Context.Provider>};export const useStore=()=>{const c=useContext(Context);if(!c)throw Error('Store missing');return c};
